[build]
  command = "vite build"
  functions = "functions/"
  publish = "dist"

[dev]
  framework = "vite"
  command = "vite"
  targetPort = 5173
  port = 8888
  [dev.https]
    certFile = "localhost.crt"
    keyFile = "localhost.key"