[build]
  command = "vite build"
  functions = "functions/"
  publish = "dist"

[dev]
  framework = "vite"
  command = "vite"
  targetPort = 5173
  port = 8888

[[plugins]]
  package = "netlify-plugin-js-obfuscator"
  # https://github.com/javascript-obfuscator/javascript-obfuscator.
  [plugins.inputs]
   # Compact code output on one line.
     compact = true
   # Enables numbers conversion to expressions
     numbersToExpressions = true
   # Enables additional code obfuscation through simplification.
     simplify = true
   # Randomly shuffles the stringArray array items
     shuffleStringArray = true
   # Splits literal strings into chunks with length of splitStringsChunkLength option value
     splitStrings = true